### ISSUE TITLE
Attempt to call method 'GetItemValue' (a nil value)

### ISSUE THREAD

**Issue by LaDzi** [Tercioo/Auto-Seller#3]
Hey, got Auto-Seller and TSM 4 installed.
When I try to sell a green Item I am gettting the following error.

I am not familiar with Lua but it seems, that the error is within in Line 172.

local price = TSM:GetItemValue (itemLink, "DBMarket")

Tried other TSM Functions but none seem to work. Right now I am returning average_price.
Then it should work, as if no other addon is installed.

Sorry to bother you, would love to fix it myself, but would be nice to see a solution for this one.

24x SYH\AutoSeller.lua:172: attempt to call method 'GetItemValue' (a nil value)
[string "@SYH\AutoSeller.lua"]:1401: in function <SYH\AutoSeller.lua:1332>
[string "=(tail call)"]: ?
[string "=[C]"]: in function `xpcall'
[string "@LibDFramework-1.0\fw.lua"]:3644: in function `CoreDispatch'
[string "@LibDFramework-1.0\button.lua"]:921: in function <LibDFramework-1.0\button.lua:834>

**Comment by Tercioo** [comment]
Fixed, thanks for reporting.
